### PR TITLE
Optimize the dependencies

### PR DESCRIPTION
**Pull request by vinkla**
Just wanted to let you know that we could reduce the size of the vendor directory by half if we run this Composer commands:

```sh
composer update --prefer-dist --no-dev
composer dump-autoload --optimize
```

It went from 9 MB to 4.4 MB, which is awesome. We don't need the test dependencies in production. This will make installation time much faster as well. Though, in the future we should try to remove the `vendor` directory as discussed in #41.

### CODE REVIEW

**Comment by Gert-dev** [comment]
Thanks for this. I'm going to see if I can implement https://github.com/php-integrator/core/pull/41 first and, if that can't or doesn't happen soonish, I'll merge this in.

**Comment by vinkla** [comment]
:+1:

**Comment by Gert-dev** [comment]
In the next version of the base package, the core will be pulled automatically using Composer instead of via apm. I've passed these arguments there, so the development items should no longer be pulled. Thanks for the tip!

**Comment by vinkla** [comment]
Oh, that is great. I'm curious on how you did it. Could you point me to the code?

**Comment by vinkla** [comment]
Never mind, found it on my own https://github.com/php-integrator/atom-base/commit/5a06d1ef168e9b8442dc0f3e94c4321f81abe124

**Pull request closed without merging**
