### PR TITLE
remove vendor

### PR DESCRIPTION
**Pull request by fbourigault**
vendor were added accidentally when this repository was created. This commit remove the whole vendor content and add the directory to the .gitignore.

### CODE REVIEW

**Comment by Gert-dev** [comment]
Thanks for the good intention, but they kind of.. weren't added by accident [1]. The reason is that in order for it to work as an Atom package, Atom only checks out the Git repository of a package and installs its dependencies (via something like `npm`), but it never installs any Composer dependencies. 

In other words, if I remove the dependencies here, I'd need to either force Atom users to run a `composer install` every time the core is updated/redownloaded. If I want to do it automatically instead, I have to ask users to tell me where composer is installed, which brings in a myread of issues related to people using old composer versions, not having it in its path, not knowing how to install it separately, ...

What I _could_ do is remove the dependencies here and create a separate repository that just includes the vendor directories and use _that_ as a download for Atom instead. That way, this repository is clean and Atom users are happy. The only downside to that is it severely increases development overhead as I need to keep that repository in sync constantly.

[1] https://github.com/php-integrator/core#why-are-the-composer-dependencies-in-git

**Comment by fbourigault** [comment]
What about building the tool as a phar archive? it would avoid repository growing over time as dependencies are updating and probably improve the tool interoperability.

The build could be done by travis-ci like for [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/.travis.yml)

**Comment by Gert-dev** [comment]
I think I may have an idea that allows removing the dependencies and keeping Atom users happy: I already know where PHP is located, in theory I could use PHP to download the Composer phar and run it on the fly with the same PHP version to install the dependencies. After that, the downloaded Composer would just disappear.

In any case, I'll leave this open until I can investigate it further as I would like to remove the dependencies from Git, but maintaining the ease of "live" development in the meantime.

**Comment by Gert-dev** [comment]
I've removed the Composer dependencies from the development branch. The core will be installed via Composer as soon as I release the next minor/major release of the base package.

There is one remaining thing I'm not sure about: What happens to the `platform` directive in the `composer.json` file? It ensures that newer versions of dependencies that require PHP 7 don't get pulled into the lock file. I added it since we're still officially supporting PHP 5.6 and Atom users previously basically received a clone of the master branch with all the dependencies intact.

Now that the dependencies are gone, if I remove it, doesn't it still risk me pulling PHP 7 dependencies into the lock file, after which the users downloading the core (which basically just do a `composer require`) will also get the same PHP 7 dependencies? This because Composer looks at the lock file first to see what versions of dependencies to pull. This is incredibly handy in production environments such as websites, but I'm not sure the lock file should be in Git for this repository as there is no "single snapshot" of the dependencies that is required for everything to work correctly.

**Comment by vinkla** [comment]
@Gert-dev since this is fixed on `development` we could close this now.

**Comment by fbourigault** [comment]
I think you should think about the core being a library, not an application. Doing so, you should use the travis-ci matrix to installer lowest dependencies using composer --prefer-lowest switch when running tests against PHP 5.6. Symfony use this kind of configuration. Are you interested by a PR about such travis-ci setup?

**Comment by fbourigault** [comment]
PR about travis-ci matrix: #63

**Pull request closed without merging**
