### PR TITLE
Test library with Travis

### PR DESCRIPTION
**Pull request by vinkla**
Now, we only need to enable the repository on [Travis](https://travis-ci.org) to start testing. All future pull requests will be running against Travis before we merge them.

I've also added badges for build status and code coverage.

### CODE REVIEW

**Comment by Gert-dev** [comment]
Thanks! I've never worked with Travis before, but will look into enabling it soon.

**Comment by vinkla** [comment]
Cool, it is pretty easy. You basically just sign up and enable the repository and they will solve the rest.

**Comment by Gert-dev** [comment]
I've manually merged it in because it generated conflicts because I made some changes to the README. It seems to have succeeded in its initial build. Thanks!

**Comment by vinkla** [comment]
:+1:

**Pull request closed without merging**
